[package]
name = "atomic_websocket"
version = "0.2.5"
authors = ["hsng95@gmail.com"]
description = "High level Websocket util library from tokio-tungstenite"
homepage = "https://github.com/rabbitson87/atomic_websocket"
repository = "https://github.com/rabbitson87/atomic_websocket"
keywords = ["websocket", "client", "server"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.77"

[dependencies]
tokio = { version = "1.40.0", default-features = false, features = [
    "sync",
    "macros",
    "time",
    "rt-multi-thread",
] }
async-trait = "0.1.82"
native_db = "0.7.1"
native_model = "0.4.19"
tokio-tungstenite = "0.23.1"
nanoid = "0.4.0"
futures-util = "0.3.30"
log = "0.4.22"

bebop = "3.0.14"
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
serde = { version = "1.0.209", features = ["derive"] }
native-tls = { version = "0.2.12", optional = true }

[workspace]
members = ["make_bebop", "test"]

[features]
default = []
debug = []
native_tls = ["dep:native-tls", "tokio-tungstenite/native-tls"]
